include missing dependency to javax.servlet artifact, fixes NoClassDefFoundError: javax/servlet/ServletContainerInitializer
git-svn-id: https://svn.java.net/svn/jersey~svn/trunk/jersey@4975 2fda5173-fe30-0410-90bd-98ff5453417f